### PR TITLE
feat: Support ignoring members with a regex pattern

### LINKED ISSUE #21: Allow specifying regex in PackageDiffIgnore.xml
For context: Fixing https://github.com/unoplatform/uno/issues/11241 will remove **lots** of methods, and having to specify all of them is noisy.

We can allow:

```xml
<Member fullName=".+?ApplyCompiledBindings\(\)" isRegex="true" />
```

@jeromelaban thoughts?

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #21 (I'm not certain what the intent of https://github.com/unoplatform/Uno.PackageDiff/issues/21#issuecomment-1531419436 is, @Xiaoy312 let me know if there is something I should adjust here)

## PR Type
What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Xiaoy312** [comment]
so long as you are not prefixing & suffixing input regex with ^$ to make it a full match, that is good

**Comment by jeromelaban** [comment]
@Youssef1313 Nice! Can you update the readme as well?

**Review by jeromelaban — APPROVED** [review]

**Comment by Youssef1313** [comment]
@jeromelaban Can we get this merged?

**Comment by jeromelaban** [comment]
Let's fix the build first :)

**Pull request merged**
